name: "⚠️ Report an Issue"
description: "Something Not Working Right? Please let us know..."
labels: ["bug"]
assignees:
  - smashedr

body:
  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: Details
      description: Please describe the issue you are experiencing and how to reproduce.
      placeholder: Provide as many details as you can...

  - type: textarea
    id: logs
    validations:
      required: true
    attributes:
      label: Support Information
      description: Open the extension options, scroll to the bottom, click Copy Support Information and paste below.
      render: shell

  - type: markdown
    attributes:
      value: |
        All issues/bugs that we can verify will be fixed. Thank you for taking the time to make this report!
